GEODESTINOSEC_sys/GEODESTINOSEC_sys/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path("select2/", include("django_select2.urls")),
    path('', views.LoginView.as_view(template_name='sysuserprofile/login.html'), name='index'),
    path('dashboard/', include('dashboard.urls')),
    path('dashboard/clients/', include('clients.urls')),
    path('dashboard/analytics/', include('analytics.urls')),
    path('admin/', admin.site.urls),
    path('login/', views.LoginView.as_view(template_name='sysuserprofile/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GEODESTINOSEC_sys/clients/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.clients_visualize, name='clients'), #TODO HTML base for clients
    path('new-client/', views.clients_create, name='new_client'), #TODO create form -> clients
    path('search/', views.search_name, name='search_name'),    # - search engine of clients
    path('<pk>/', views.clients_read_update, name='clients_read_update'),#TODO update form -> clients

    path('visa/<pk>/', views.visa_create, name='visa_create'), #TODO create form -> visa
    path('visa-delete/<pk>/', views.visa_delete, name='visa_delete'), #TODO delete form -> visa
    path('visa-loading/<pk>/', views.visa_loading, name='visa_loading'), #TODO HTML base for visa
    path('passport/<pk>/', views.passport_create, name='passport_create'), #TODO create form -> passport
    path('passport-delete/<pk>/', views.passport_delete, name='passport_delete'), #TODO delete form -> passport
    path('passport-loading/<pk>/', views.passport_loading, name='passport_loading'), #TODO HTML base for passport
    
    path('/get-regions/', views.get_regions, name='get_regions'), #TODO get regions from country
    path('/get-cities/', views.get_cities, name='get_cities'), #TODO get cities from country
    ]

GEODESTINOSEC_sys/clients/models.py
from django.db import models
from django.core.validators import RegexValidator
from static.metadata_dictionaries import *
from phonenumber_field.modelfields import PhoneNumberField
import cities_light

class Client(models.Model):
    # nro, primary key, 10 o passport -> validar con algoritmo?
    id_number = models.CharField(max_length=20, primary_key=True, null=False, blank=False, validators=[
        RegexValidator(regex='(^\d{10}|^[a-zA-Z0-9]*)$', message='Error ID/RUC/Pasaporte no válido!', code='nomatch')])
    
    id_type = models.CharField(max_length=3, null=True, choices=ID_TYPE_CHOICES, default='None')
    
    client_type = models.CharField(max_length=2, null=False, choices=CLIENT_TYPE_CHOICES, default='P')

    first_name = models.CharField(max_length=20, null=False)
    second_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=20, null=False)
    sur_name = models.CharField(max_length=20, blank=True, null=True)
    # Generate the fullname from the first_name, second_name, last_name, and sur_name

    image = models.ImageField(upload_to='clients_photos', null=True, blank=True)
    
    gender = models.CharField(max_length=2, null=True, choices=GENDER_CHOICES, blank=True, default=None)
    
    civil_status = models.CharField(max_length=2, null=True, 
                                    blank=True, choices=CIVIL_STATUS_CHOICES, default=None)
    # +593 ++ 9 dígitos -> validate! 13 exactly
    
    phone = PhoneNumberField(null=False)
    email = models.EmailField(max_length=50, null=False, blank=False)
    
    # current session user
    salesman_refer = models.ForeignKey('sysuserprofile.UserProfile', on_delete=models.SET_NULL, null=True, blank=True)  
    
    # TODO EXTRACT city.province & city.country from the city_light model
    res_city = models.ForeignKey('cities_light.City', related_name='cities', on_delete=models.SET_NULL, null=True, blank=True, default=None)
    res_region = models.ForeignKey('cities_light.Region', related_name='regions', on_delete=models.SET_NULL, null=True, blank=True, default=None)
    res_country = models.ForeignKey('cities_light.Country', related_name='countries', on_delete=models.SET_NULL, null=True, blank=True, default=None)
    address = models.TextField(max_length=100, null=True, blank=True, default=None)
    
    person_type = models.CharField(max_length=4, null=True, blank=True, choices=PERSON_TYPE_CHOICES, default=None)
        
    date_of_birth = models.DateField(null=True, blank=True)
    
    budget_capacity = models.CharField(max_length=2, null=True, blank=True, default=None, choices=BUDGET_CAPACITY_CHOICES)

    academic_level = models.CharField(max_length=2, null=True, blank=True, default=None, choices=ACADEMIC_LEVEL_CHOICES)
    work_type = models.CharField(max_length=2, null=True, blank=True, default=None, choices=WORK_TYPE_CHOICES)
    work_industry = models.CharField(max_length=5, null=True, blank=True, default=None, choices=WORK_INDUSTRY_CHOICES)
    work_position = models.CharField(max_length=50, null=True, blank=True, default=None)
    company_name = models.CharField(max_length=50, null=True, blank=True, default=None)
    additional_info = models.TextField(max_length=100, null=True, blank=True, default=None)
    


    def __str__(self):
        return f'{self.first_name} {self.last_name} --- {self.id_number}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
    
class Visa(models.Model):
    visa_holder = models.ForeignKey('Client', on_delete=models.CASCADE, null=False, blank=False)
    visa_number = models.CharField(primary_key=True, max_length=20, null=False)
    visa_type = models.CharField(max_length=3, null=False, choices=VISA_TYPE_CHOICES, default='T')
    visa_issue_date = models.DateField(null=False)
    visa_expire_date = models.DateField(null=False)
    visa_to_country = models.ForeignKey('cities_light.Country', on_delete=models.CASCADE, null=False, blank=False)
    
    def __str__(self):
        return f'{self.visa_holder} --- {self.visa_type} {self.visa_number}'
    
class Passport(models.Model):
    passport_holder = models.ForeignKey('Client', on_delete=models.CASCADE, null=False, blank=False)
    passport_number = models.CharField(primary_key=True, max_length=20, null=False)
    passport_type = models.CharField(max_length=3, null=False, choices=PASSPORT_TYPE_CHOICES)
    passport_issue_date = models.DateField(null=False)
    passport_expire_date = models.DateField(null=False)
    passport_issue_country = models.ForeignKey('cities_light.Country', on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return f'{self.passport_holder} --- {self.passport_number}'

GEODESTINOSEC_sys/clients/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, JsonResponse
from django.db.models import Q
from cities_light.models import City, Region, Country
from .forms import AddClientForm, ReadUpdateClientForm, AddVisaForm, AddPassportForm
from .models import Client, Visa, Passport
from django.contrib import messages



# This is for the "Buscar cliente" bar in the main page in dashboard/clients/
@login_required
def search_name(request):
    query_string = request.GET.get('q')
    if query_string:
        query_list = query_string.split()
        queries = [Q(id_number__icontains=term) |
                   Q(first_name__icontains=term) | 
                   Q(second_name__icontains=term) | 
                   Q(last_name__icontains=term) | 
                   Q(sur_name__icontains=term) for term in query_list]
        query = queries.pop() if queries else Q()
        for item in queries:
            query |= item
        clients = Client.objects.filter(query)
    else:
        clients = Client.objects.all()
    return render(request, 'clients/clients_search_result.html', {'clients': clients})

# This sort the clients by name and last name and display in the main page chart
@login_required
def clients_visualize(request):
    clients = Client.objects.all().order_by(
        'first_name', 'second_name', 'last_name', 'sur_name')
    return render(request, 'clients/clients.html', {
        'clients': clients
    })

# Open the form with a button, id_type is extracted from id_number
# Called by form that register clients
@login_required 
def clients_create(request):
    if request.method == 'POST':
        form = AddClientForm(request.POST, request.FILES)
        if form.is_valid():
            User = get_user_model()
            form.salesman_refer = User.objects.get(username=request.user.username).userprofile
            form.save()

            return redirect('/dashboard/clients/')            
        else:
            #cache.set('cached_cities', City.objects.all(), 60*60*2) # Set Cities in cache for 2 hours every time the model is accessed
            return render(request, 'clients/new_client.html',
                    {'form': form})
    else:

        form = AddClientForm()
        return render(request, 'clients/new_client.html',
                    {'form': form})
    
@login_required
def get_regions(request, *args, **kwargs):
    if request.method == 'GET':
        country_id = request.GET.get('country')
        try:
            regions = Region.objects.filter(country=country_id)
            data = [{'id': '', 'name': '---------'}]
            data += [{'id': region.id, 'name': region.name} for region in regions]
            return JsonResponse(data, safe=False)
        except ValueError:
            data = [{'id': '', 'name': '---------'}]
            return JsonResponse(data, safe=False)
    else:
        return JsonResponse({'error': 'Not a valid request'})
    
@login_required
def get_cities(request):
    if request.method == 'GET':
        region_id = request.GET.get('region')
        cities = City.objects.filter(region=region_id)
        data = [{'id': '', 'name': '---------'}]
        data += [{'id': city.id, 'name': city.name} for city in cities]
        return JsonResponse(data, safe=False)
    else:
        return JsonResponse({'error': 'Not a valid request'})

    
# Call to the client data, then display in the form with tabs
# just to visualize unless the user wants to update the data
@login_required
def clients_read_update(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = ReadUpdateClientForm(request.POST, request.FILES, instance=client)
        if (request.POST.get('id_number') != client.id_number) and form.is_valid():
            form.save()
            messages.warning(request, f'El número de ID de "{request.POST.get("first_name")} {request.POST.get("last_name")}" ha sido cambiado a {request.POST.get("id_number")}!')
            old_client = get_object_or_404(Client, pk=pk)
            old_client.delete()
            return redirect('/dashboard/clients/')
        else:
            form.full_clean()
            form.save()
            return redirect('/dashboard/clients/')
    else:
        form = ReadUpdateClientForm(instance=client)
    
    return render(request, 'clients/read_update_client.html',
                        {'form': form, 'client': client})

@login_required
def visa_loading(request, pk):
    client = get_object_or_404(Client, pk=pk)
    visas = Visa.objects.filter(visa_holder=client)
    return render(request, 'clients/loading_visa.html',
                    {'visas': visas})

@login_required
def passport_loading(request, pk):
    client = get_object_or_404(Client, pk=pk)
    passports = Passport.objects.filter(passport_holder=client)
    return render(request, 'clients/loading_passport.html',
                    {'passports': passports})

@login_required
def visa_create(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = AddVisaForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Visa created!')
            return HttpResponseRedirect(reverse('clients_read_update', args=[pk]))
        else:
            messages.error(request, 'Visa not created!')
    else:
        form = AddVisaForm(initial={'visa_holder': client.pk})
    return render(request, 'clients/visa_create.html',
                    {'form': form, 'client': client})

@login_required
def visa_delete(request, pk):
    visa = get_object_or_404(Visa, pk=pk)
    messages.success(request, f'Visa to {visa.visa_to_country }, Nro: {visa.visa_number} deleted!')
    visa.delete()
    return redirect('clients_read_update', visa.visa_holder.pk)

@login_required
def passport_create(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = AddPassportForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Passport created!')
            return HttpResponseRedirect(reverse('clients_read_update', args=[pk]))
        else:
            messages.error(request, 'Passport not created!')
    else:
        form = AddPassportForm(initial={'passport_holder': client.pk})
    return render(request, 'clients/passport_create.html',
                    {'form': form, 'client': client})

@login_required
def passport_delete(request, pk):
    passport = get_object_or_404(Passport, pk=pk)
    messages.success(request, f'Passport from {passport.passport_issue_country }, Nro: {passport.passport_number} deleted!')
    passport.delete()
    return redirect('clients_read_update', passport.passport_holder.pk)

GEODESTINOSEC_sys/clients/templates/clients/clients.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} Administrador de Clientes {% endblock %}

{% block content %}
<!-- TODO fixed location of the bar and the chart, 
    do not change size when display-->
    
<div class="flex justify-between py-3 px-4 space-x-4">
    <a href="{% url 'new_client' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Nuevo Cliente</a>

    {% csrf_token %}
    <input type="text" name="q" 
            id="search-input" class="border border-gray-300 rounded-lg p-2"
            placeholder="Buscar cliente"
            hx-get="{% url 'search_name' %}"
            hx-target="#search-results"
            hx-trigger="input delay:10ms">
</div>

<div class="py-3 px-4">
    <table class="justify-between" style="width: 100%;">
        <thead class="py-4 bg-gray-600 text-white">
            <tr>
                <th class="py-2">Nombre completo</th>
                <th class="py-2">Número de ID</th>
                <th class="py-2">Tipo de ID</th>
                <th class="py-2">Fecha de nacimiento</th>
                <th class="py-2">Acciones</th>
            </tr>
        </thead>
        
        <tbody id="search-results">
            {% for client in clients %}
            <tr class="text-center align-middle {% cycle 'bg-gray-100' '' %}">
                <td class="py-2 px-4">{{ client.first_name }} {{ client.second_name|default:'' }} {{ client.last_name }} {{ client.sur_name|default:'' }}</td>
                <td class="py-2 px-4">{{ client.id_number }}</td>
                <td class="py-2 px-4">{{ client.id_type }}</td>
                <td class="py-2 px-4">{{ client.date_of_birth }}</td>
                <td class="py-2 px-4"><a href="{% url 'clients_read_update' client.pk %}" target="_self" class="px-4 py-1 bg-green-400 hover:bg-green-600 text-white rounded-xl">Ver / Modificar</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   
</div>
{% endblock %}

GEODESTINOSEC_sys/clients/templates/clients/clients_search_result.html
{% if not clients %}
    <p class="px-4 py-2 w-full text-center">No se encontró un usuario con ese nombre...</p> 
{% else %}
    {% for client in clients %}
    <tr class="text-center align-middle {% cycle 'bg-gray-100' '' %}">
        <td class="py-2 px-4">{{ client.first_name }} {{ client.second_name|default:'' }} {{ client.last_name }} {{ client.sur_name|default:'' }}</td>
        <td class="py-2 px-4">{{ client.id_number }}</td>
        <td class="py-2 px-4">{{ client.id_type }}</td>
        <td class="py-2 px-4">{{ client.date_of_birth }}</td>
        <td class="py-2 px-4"><a href="{% url 'clients_read_update' client.pk %}" target="_self" class="px-4 py-1 bg-green-400 hover:bg-green-600 text-white rounded-xl">Ver / Modificar</a></td>
    </tr>
    {% endfor %}
{% endif %}

GEODESTINOSEC_sys/clients/templates/clients/loading_passport.html
<h2 class="text-center text-xl font-bold text-white"> Pasaportes registrados </h2>
{% if not passports %}
<div class="inline-block my-3 w-2/3 text-center px-1 py-1 form-group border-2 rounded-lg border-gray-500 bg-gray-50">
    <h2 class="text-l font-bold my-5"> No se ha encontrado ningún pasaporte registrado para este cliente </h2>
</div>    
{% else %}
<div class="grid grid-cols-2 gap-1 mx-1 px-1 py-1 form-group">
    {% for passport in passports %}
    <div class="text-center px-1 py-1 form-group border-2 rounded-lg border-gray-500 bg-gray-50">
        <h2 class="mb-2 text-l font-bold text-white bg-teal-500 rounded-lg text-center">Pasaporte ({{ passport.passport_issue_country }})</h2>
        <div class="flex flex-row border-b border-gray-400 my-3">
            <label class="w-1/4 text-xs font-bold">Número y tipo: </label>
            <p class="w-3/4 text-m font-bold">{{ passport.passport_number }} - {{ passport.passport_type }}</p> 
        </div>
        <div class="flex flex-row border-b border-gray-400 my-3">
            <label class="w-1/4 text-xs font-bold">Fecha de expedición: </label>
            <p class="w-3/4 text-m font-bold">{{ passport.passport_issue_date }}</p>
        </div>
        <div class="flex flex-row border-b border-gray-400 my-3">
            <label class="w-1/4 text-xs font-bold">Fecha de expiración: </label>
            <p class="w-3/4 text-m font-bold">{{ passport.passport_expire_date }}</p>
        </div>
        <form action="{% url 'passport_delete' passport.pk %}" method="POST">
            {% csrf_token %}
            <button id='editable' class="pointer-events-none opacity-50 px-2 py-1 bg-red-500 hover:bg-red-600 text-white rounded-xl"> Eliminar </button>
        </form>
    </div>
    {% endfor %}
</div>
{% endif %}

GEODESTINOSEC_sys/clients/templates/clients/new_client.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} Nuevo Cliente {% endblock %}

{% block content %}
<div class = 'py-1 px-1'>
    {% load tailwind_filters %}
    {% load crispy_forms_tags %}
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% crispy form %}
        <!--{{ form|crispy }}-->
    </form>

</div>
{% endblock %}

{% block scripts %}
<script>
    $("#id_res_country").select2({
        closeOnSelect: true,
        caches: true,
    });
    
    $("#id_res_region").select2({
        closeOnSelect: true,
        caches: true,
        placeholder: 'Selecciona primero un país',
    });
    $("#id_res_city").select2({
        closeOnSelect: true,
        caches: true,
        placeholder: 'Selecciona primero una región',
    });
</script>
<script>
    $(document).ready(function() {
    $("#id_res_country").change(function() {
        var countryId = $(this).val();
        $.ajax({
            url: "{% url 'get_regions' %}",
            data: {'country': countryId},
            dataType: 'json',
            success: function(data) {
                $("#id_res_region").empty();
                $.each(data, function(index, region) {
                    $("#id_res_region").append('<option value="' + region.id + '">' + region.name + '</option>');
                });
                $("#id_res_city").empty();
            }
        });
    });

    $("#id_res_region").change(function() {
        var regionId = $(this).val();
        $.ajax({
            url: "{% url 'get_cities' %}",
            data: {'region': regionId},
            dataType: 'json',
            success: function(data) {
                $("#id_res_city").empty();
                $.each(data, function(index, city) {
                    $("#id_res_city").append('<option value="' + city.id + '">' + city.name + '</option>');
                });
            }
        });
    });
});
</script>

{% endblock %}

{% block stylesheets %}
<style>
    .select2-container{
        border: 1px solid #e2e8f0;
        border-radius: .5rem;
        line-height: 1.5;
        padding: .5rem 1rem .5rem 1rem;
        background-color: white;
        border-width: 1px;
    } 
    .select2-container--default .select2-selection--single{
        border: none;
    }

    .select2-selection__arrow {
        display: none;
    }

    body {
    --iuw-background: white !important;
    --iuw-border-color: rgb(209 213 219 ) !important;
    --iuw-color: #{$dashgray} !important;
    --iuw-placeholder-text-color: #{$dashgray} !important;
    --iuw-dropzone-background: white !important;
    --iuw-image-preview-border: rgb(209 213 219) !important;
    --iuw-image-preview-shadow: rgba(171, 170, 170, 0.3);
    --iuw-add-image-background: #{$dashlight} !important;
    --iuw-add-image-color: #{$dashgray} !important;
    }
</style>
{% endblock %}

GEODESTINOSEC_sys/clients/templates/clients/passport_create.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} Nueva Visa {% endblock %}
{% block content %}
    <div class = 'py-1 px-1'>
        {% load tailwind_filters %}
        {% load crispy_forms_tags %}
        <form method="post" action=".">
            {% csrf_token %}
            {% crispy form %}
            <!--{{ form|crispy }}-->
        </form>
    </div>
{% endblock %}
{% block scripts %}
<script>
    $("#id_visa_to_country").select2({
        closeOnSelect: true,
        minimumInputLength: 1,
        caches: true,
        maximumSelectionLength: 10,
    });
</script>
{% endblock %}
{% block stylesheets %}
<style>
    .select2-container{
        border: 1px solid #e2e8f0;
        border-radius: .5rem;
        line-height: 1.5;
        padding: .5rem 1rem .5rem 1rem;
        background-color: white;
        border-width: 1px;
    } 
    .select2-container--default .select2-selection--single{
        border: none;
    }

    body {
    --iuw-background: white !important;
    --iuw-border-color: rgb(209 213 219 ) !important;
    --iuw-color: #{$dashgray} !important;
    --iuw-placeholder-text-color: #{$dashgray} !important;
    --iuw-dropzone-background: white !important;
    --iuw-image-preview-border: rgb(209 213 219) !important;
    --iuw-image-preview-shadow: rgba(171, 170, 170, 0.3);
    --iuw-add-image-background: #{$dashlight} !important;
    --iuw-add-image-color: #{$dashgray} !important;
    }

    .select2-selection__arrow {
        display: none;
    }
</style>
{% endblock %}

GEODESTINOSEC_sys/clients/templates/clients/read_update_client.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} Editar Cliente {% endblock %}

{% block content %}

<div>

    {% load crispy_forms_tags %}
    <form method="POST" action="." id="view-edit-form" enctype="multipart/form-data">
        {% csrf_token %}
        {% crispy form %}
    </form>
</div>
{% endblock %}

{% block scripts %}
<script>
    $("#id_res_country").select2({
        closeOnSelect: true,
        caches: true,
    });
    $("#id_res_region").select2({
        closeOnSelect: true,
        caches: true,
        placeholder: 'Selecciona primero un país',
    });
    $("#id_res_city").select2({
        closeOnSelect: true,
        caches: true,
        placeholder: 'Selecciona primero una región',
    });
</script>
<script>
    $(document).ready(function() {
    $("#id_res_country").change(function() {
        var countryId = $(this).val();
        $.ajax({
            url: "{% url 'get_regions' %}",
            data: {'country': countryId},
            dataType: 'json',
            success: function(data) {
                $("#id_res_region").empty();
                $.each(data, function(index, region) {
                    $("#id_res_region").append('<option value="' + region.id + '">' + region.name + '</option>');
                });
                $("#id_res_city").empty();
            }
        });
    });

    $("#id_res_region").change(function() {
        var regionId = $(this).val();
        $.ajax({
            url: "{% url 'get_cities' %}",
            data: {'region': regionId},
            dataType: 'json',
            success: function(data) {
                $("#id_res_city").empty();
                $.each(data, function(index, city) {
                    $("#id_res_city").append('<option value="' + city.id + '">' + city.name + '</option>');
                });
            }
        });
    });
});
</script>
<script>
    //BY DEFAULT, DISABLE THE FORM FIELDS 
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('#view-edit-form select, #editable, #id_res_country, #id_res_region, #id_res_city').forEach(function(element) {
            element.classList.add('pointer-events-none');
            element.classList.add('opacity-50');
            element.disabled = true;
        });
        var deleteIcon = document.querySelectorAll('.iuw-delete-icon');
        deleteIcon.forEach(function(icon) {
            icon.style.display = 'none';
        });
    });

    // Enable the form fields for editing
    document.addEventListener('DOMContentLoaded', function () {
        document.getElementById('edit-button').addEventListener('click', function() {
            document.querySelectorAll('#view-edit-form select, #id_res_country, #id_res_region, #id_res_city, #id_date_of_birth_day, #id_date_of_birth_month, #id_date_of_birth_year, #editable, #id_phone_0, #id_phone_1').forEach(function(element) {
                element.classList.remove('pointer-events-none');
                element.classList.remove('opacity-50');
                element.disabled = false;
            });
            document.getElementById('edit-button').style.display = 'none';                                   
            document.getElementById('submit-button').style.display = 'block';
            var deleteIcon = document.querySelectorAll('.iuw-delete-icon');
            deleteIcon.forEach(function(icon) {
                icon.style.display = 'flex';
            });
        });
    });

    // Tabs behavior to divs in edit-view client
    document.addEventListener('DOMContentLoaded', function () {
        var tabButtons = document.querySelectorAll('.show-div');
        var tabContents = document.querySelectorAll('.tab-content');
        tabButtons.forEach(function(button) {
            button.addEventListener('click', function() {
                var targetId = button.getAttribute('data-target');
                tabButtons.forEach(function(btn) {
                    btn.classList.remove('active');
                    btn.classList.remove('text-black');
                    btn.classList.remove('bg-white');
                    btn.classList.add('text-white');
                    btn.classList.add('bg-gray-500');
                });
                button.classList.remove('text-white');
                button.classList.remove('bg-gray-500');
                button.classList.add('active');
                button.classList.add('text-black');
                button.classList.add('bg-white');

                tabContents.forEach(function(content) {
                    content.style.display = 'none';
                });
                document.querySelector(targetId).style.display = 'flex';
            });
        });
    });

</script>
{% endblock %}

{% block stylesheets %}
<style>
    body {
        --iuw-background: white !important;
        --iuw-border-color: rgb(209 213 219 ) !important;
        --iuw-color: #{$dashgray} !important;
        --iuw-placeholder-text-color: #{$dashgray} !important;
        --iuw-dropzone-background: white !important;
        --iuw-image-preview-border: rgb(209 213 219) !important;
        --iuw-image-preview-shadow: rgba(171, 170, 170, 0.3);
        --iuw-add-image-background: #{$dashlight} !important;
        --iuw-add-image-color: #{$dashgray} !important;
        }

    .select2-container{
        border: 1px solid #e2e8f0;
        border-radius: .5rem;
        line-height: 1.5;
        padding: .5rem 1rem .5rem 1rem;
        background-color: white;
        border-width: 1px;
    } 

    .select2-container--default .select2-selection--single{
        border: none;
        width: 100%;
    }

    .select2-selection__arrow {
        display: none;
    }

    
</style>
{% endblock %}

GEODESTINOSEC_sys/clients/templates/clients/visa_create.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %} Nueva Visa {% endblock %}
{% block content %}
    <div class = 'py-1 px-1'>
        {% load tailwind_filters %}
        {% load crispy_forms_tags %}
        <form method="post" action=".">
            {% csrf_token %}
            {% crispy form %}
            <!--{{ form|crispy }}-->
        </form>
    </div>
{% endblock %}
{% block scripts %}
<script>
    $("#id_visa_to_country").select2({
        closeOnSelect: true,
        minimumInputLength: 1,
        caches: true,
        maximumSelectionLength: 10,
    });
</script>
{% endblock %}
{% block stylesheets %}
<style>
    .select2-container{
        border: 1px solid #e2e8f0;
        border-radius: .5rem;
        line-height: 1.5;
        padding: .5rem 1rem .5rem 1rem;
        background-color: white;
        border-width: 1px;
    } 
    .select2-container--default .select2-selection--single{
        border: none;
    }

    body {
    --iuw-background: white !important;
    --iuw-border-color: rgb(209 213 219 ) !important;
    --iuw-color: #{$dashgray} !important;
    --iuw-placeholder-text-color: #{$dashgray} !important;
    --iuw-dropzone-background: white !important;
    --iuw-image-preview-border: rgb(209 213 219) !important;
    --iuw-image-preview-shadow: rgba(171, 170, 170, 0.3);
    --iuw-add-image-background: #{$dashlight} !important;
    --iuw-add-image-color: #{$dashgray} !important;
    }

    .select2-selection__arrow {
        display: none;
    }
</style>
{% endblock %}